services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uv run uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: heslo123
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
